import "./globals.css";

import { AuthProvider } from "../context/AuthContext";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Toaster } from "sonner";
import localFont from "next/font/local";

const switzer = localFont({
  src: "./fonts/Switzer Variable.woff2",
  display: "swap",
  variable: "--font-switzer",
  style: "normal",
  weight: "400 700",
});

const geistPoppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistPoppins.variable} ${switzer.variable} antialiased`}
      >
        <AuthProvider>{children}</AuthProvider>
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
